# This is an example urls.yaml file for urlwatch

name: "urlwatch Nikki Haley"
url: "https://nikkihaley.com/about/"
filter:
  - element-by-class: "content"
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch George Santos"
url: "https://georgeforny.com/about/"
filter:
  - element-by-class: "row"
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch Josh Hawley"
url: "https://joshhawley.com/"
filter:
  - xpath: /html/body/div[1]/div/div/section[6]/div[3]/div/div[1]/div/div
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch Donald Trump"
url: "https://www.donaldjtrump.com/mission"
filter:
  - element-by-class: "container"
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch Vivek"
url: "https://www.vivek2024.com/meet-vivek"
filter:
  - element-by-class: "paragraph-4"
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch Marianne"
url: "https://marianne2024.com/meet-marianne/"
filter:
  - element-by-class: "entry-content"
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch test"
url: "https://www.greenbeltnewsreview.com/news-stories/"
filter:
  - element-by-class: "entry-content"
  - html2text
  - strip
  - diff_tool: wdiff
---

---
name: "urlwatch test-NOVA"
url: "https://northernvirginiamag.com/"
filter:
  - element-by-class: "article-excerpt"
  - html2text
  - strip
  - diff_tool: wdiff
---